export const products = [
  {
    id: 1,
    title: "Premium Website Template",
    description: "A highly responsive and stunning website template for professional businesses.",
    price: "$49",
    category: "Web Templates",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=600&h=400",
    features: ["Responsive Design", "SEO Optimized", "Fast Loading", "Premium Support"],
  },
  {
    id: 2,
    title: "UI/UX Design Kit",
    description: "Complete UI/UX design kit with hundreds of components for Figma and Sketch.",
    price: "$79",
    category: "Design Assets",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=600&h=400",
    features: ["500+ Components", "Auto Layout", "Icon Set Included", "Free Updates"],
  },
  {
    id: 3,
    title: "React Admin Dashboard",
    description: "A powerful admin dashboard built with React and Tailwind CSS.",
    price: "$99",
    category: "Dashboards",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600&h=400",
    features: ["Dark Mode", "Data Visualization", "Authentication", "Redux State"],
  },
  {
    id: 4,
    title: "Mobile App Template",
    description: "Cross-platform mobile app template built utilizing React Native.",
    price: "$59",
    category: "Mobile Templates",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&q=80&w=600&h=400",
    features: ["iOS & Android", "Push Notifications", "Clean Code", "API Ready"],
  },
  {
    id: 5,
    title: "E-Commerce Frontend",
    description: "A beautiful, fully functional e-commerce frontend interface.",
    price: "$89",
    category: "E-commerce",
    image: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&q=80&w=600&h=400",
    features: ["Cart functionality", "Product Search", "Filter System", "Stripe Ready"],
  },
  {
    id: 6,
    title: "SEO Optimization Tool",
    description: "Software tool to audit your website's SEO performance.",
    price: "$29/mo",
    category: "Software",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=600&h=400",
    features: ["Keyword Tracking", "Backlink Analysis", "Competitor Data", "Weekly Reports"],
  }
];
